SET QUOTED_IDENTIFIER ON
GO 
SET ANSI_NULLS ON 
GO 
 
IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[SP_COMPANY_INSERT]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1) 
DROP PROCEDURE [DBO].[SP_COMPANY_INSERT] 
GO 

CREATE PROCEDURE SP_COMPANY_INSERT 
( 
	@COMPANY_CNPJ       CHAR(14),
    @COMPANY_NAME       VARCHAR(60),
    @COMPANY_POSTALCODE CHAR(8),
    @COMPANY_STATE      CHAR(2) 
) 

AS 

INSERT INTO COMPANY 
    (COMPANY_CNPJ, COMPANY_NAME, COMPANY_POSTALCODE, COMPANY_STATE) 
VALUES 
    (@COMPANY_CNPJ, @COMPANY_NAME, @COMPANY_POSTALCODE, @COMPANY_STATE)

GO 
SET QUOTED_IDENTIFIER OFF 
GO 
SET ANSI_NULLS ON 
GO 