SET QUOTED_IDENTIFIER ON
GO 
SET ANSI_NULLS ON 
GO 
 
IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[SP_COMPANY_SUPPLIER_INSERT]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1) 
DROP PROCEDURE [DBO].[SP_COMPANY_SUPPLIER_INSERT] 
GO 

CREATE PROCEDURE SP_COMPANY_SUPPLIER_INSERT 
( 
	@COMPANY_CNPJ CHAR(14),
	@SUPPLIER_CPF_CNPJ CHAR(14)
) 

AS 

INSERT INTO COMPANY_SUPPLIER 
    (COMPANY_CNPJ, SUPPLIER_CPF_CNPJ) 
VALUES 
    (@COMPANY_CNPJ, @SUPPLIER_CPF_CNPJ)

GO 
SET QUOTED_IDENTIFIER OFF 
GO 
SET ANSI_NULLS ON 
GO 