SET QUOTED_IDENTIFIER ON
GO 
SET ANSI_NULLS ON 
GO 
 
IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[SP_COMPANY_SUPPLIER_SELECT]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1) 
DROP PROCEDURE [DBO].[SP_COMPANY_SUPPLIER_SELECT] 
GO 
 
CREATE PROCEDURE SP_COMPANY_SUPPLIER_SELECT
( 
	@CPF_CNPJ CHAR(14),
	@NAME VARCHAR(60)
) 

AS 

SELECT DISTINCT
	CMP_SUP.COMPANY_CNPJ,
	CMP.COMPANY_NAME,
	CMP.COMPANY_STATE,
	SUP.SUPPLIER_CPF_CNPJ,
	SUP.SUPPLIER_NAME,
	SUP.SUPPLIER_TYPE,
	SUP.SUPPLIER_RG,
	SUP.SUPPLIER_EMAIL,
	SUP.SUPPLIER_BIRTHDATE	
FROM 
	COMPANY_SUPPLIER CMP_SUP WITH(NOLOCK) 

	INNER JOIN COMPANY CMP WITH(NOLOCK) ON
		CMP.COMPANY_CNPJ = CMP_SUP.COMPANY_CNPJ

	INNER JOIN SUPPLIER SUP WITH(NOLOCK) ON
		SUP.SUPPLIER_CPF_CNPJ = CMP_SUP.SUPPLIER_CPF_CNPJ
WHERE  
	(
		@CPF_CNPJ IS NULL OR 
		CMP_SUP.COMPANY_CNPJ = @CPF_CNPJ OR
		CMP_SUP.SUPPLIER_CPF_CNPJ = @CPF_CNPJ
	)
	AND
	(
		@NAME IS NULL OR 
		CMP.COMPANY_NAME LIKE '%' + @NAME + '%' OR
		SUP.SUPPLIER_NAME LIKE '%' + @NAME + '%'
	)

GO 
SET QUOTED_IDENTIFIER OFF 
GO 
SET ANSI_NULLS ON 
GO 
