SET QUOTED_IDENTIFIER ON
GO 
SET ANSI_NULLS ON 
GO 
 
IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[SP_COMPANY_UPDATE]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1) 
DROP PROCEDURE [DBO].[SP_COMPANY_UPDATE] 
GO 
 
CREATE PROCEDURE SP_COMPANY_UPDATE 
( 
	@COMPANY_CNPJ       CHAR(14),
    @COMPANY_NAME       VARCHAR(60),
    @COMPANY_POSTALCODE CHAR(8),
    @COMPANY_STATE      CHAR(2) 
) 

AS 

UPDATE COMPANY 
SET  
    COMPANY_NAME = @COMPANY_NAME, 
    COMPANY_POSTALCODE = @COMPANY_POSTALCODE, 
    COMPANY_STATE = @COMPANY_STATE      
WHERE  
    COMPANY_CNPJ = @COMPANY_CNPJ 

GO 
SET QUOTED_IDENTIFIER OFF 
GO 
SET ANSI_NULLS ON 
GO 