SET QUOTED_IDENTIFIER ON
GO 
SET ANSI_NULLS ON 
GO 
 
IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[SP_COMPANY_DELETE]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1) 
DROP PROCEDURE [DBO].[SP_COMPANY_DELETE] 
GO 
 
CREATE PROCEDURE SP_COMPANY_DELETE
( 
	@COMPANY_CNPJ CHAR(14)
) 

AS 

DELETE FROM COMPANY_SUPPLIER  
WHERE  
    COMPANY_CNPJ = @COMPANY_CNPJ  

DELETE FROM COMPANY  
WHERE  
    COMPANY_CNPJ = @COMPANY_CNPJ

GO 
SET QUOTED_IDENTIFIER OFF 
GO 
SET ANSI_NULLS ON 
GO 