SET QUOTED_IDENTIFIER ON
GO 
SET ANSI_NULLS ON 
GO 
 
IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[SP_COMPANY_SELECT]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1) 
DROP PROCEDURE [DBO].[SP_COMPANY_SELECT] 
GO 
 
CREATE PROCEDURE SP_COMPANY_SELECT
( 
	@COMPANY_CNPJ CHAR(14)
) 

AS 

SELECT
	CMP.COMPANY_CNPJ,
	CMP.COMPANY_NAME,
	CMP.COMPANY_POSTALCODE,
	CMP.COMPANY_STATE
FROM 
	COMPANY CMP WITH(NOLOCK) 
WHERE  
    @COMPANY_CNPJ = '' OR CMP.COMPANY_CNPJ = @COMPANY_CNPJ

GO 
SET QUOTED_IDENTIFIER OFF 
GO 
SET ANSI_NULLS ON 
GO 