SET QUOTED_IDENTIFIER ON
GO 
SET ANSI_NULLS ON 
GO 
 
IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[SP_SUPPLIER_SELECT]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1) 
DROP PROCEDURE [DBO].[SP_SUPPLIER_SELECT] 
GO 
 
CREATE PROCEDURE SP_SUPPLIER_SELECT
( 
	@SUPPLIER_CPF_CNPJ CHAR(14)
) 

AS 

SELECT
	SUP.SUPPLIER_CPF_CNPJ  ,
	SUP.SUPPLIER_NAME      ,
	SUP.SUPPLIER_TYPE      ,
	SUP.SUPPLIER_EMAIL     ,
	SUP.SUPPLIER_POSTALCODE,
	SUP.SUPPLIER_RG        ,
	SUP.SUPPLIER_BIRTHDATE 
FROM 
	SUPPLIER SUP WITH(NOLOCK) 
WHERE  
	@SUPPLIER_CPF_CNPJ = '' OR SUP.SUPPLIER_CPF_CNPJ = @SUPPLIER_CPF_CNPJ

GO 
SET QUOTED_IDENTIFIER OFF 
GO 
SET ANSI_NULLS ON 
GO 	
	