SET QUOTED_IDENTIFIER ON
GO 
SET ANSI_NULLS ON 
GO 
 
IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[SP_SUPPLIER_DELETE]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1) 
DROP PROCEDURE [DBO].[SP_SUPPLIER_DELETE] 
GO 
 
CREATE PROCEDURE SP_SUPPLIER_DELETE
( 
	@SUPPLIER_CPF_CNPJ CHAR(14)
) 

AS 

DELETE FROM COMPANY_SUPPLIER  
WHERE  
    SUPPLIER_CPF_CNPJ = @SUPPLIER_CPF_CNPJ  

DELETE FROM SUPPLIER  
WHERE  
    SUPPLIER_CPF_CNPJ = @SUPPLIER_CPF_CNPJ

GO 
SET QUOTED_IDENTIFIER OFF 
GO 
SET ANSI_NULLS ON 
GO 
