SET QUOTED_IDENTIFIER ON
GO 
SET ANSI_NULLS ON 
GO 
 
IF EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[SP_SUPPLIER_UPDATE]') AND OBJECTPROPERTY(ID, N'ISPROCEDURE') = 1) 
DROP PROCEDURE [DBO].[SP_SUPPLIER_UPDATE] 
GO 
 
CREATE PROCEDURE SP_SUPPLIER_UPDATE 
( 
	@SUPPLIER_CPF_CNPJ   CHAR(14),
	@SUPPLIER_NAME       VARCHAR(60),
	@SUPPLIER_TYPE       CHAR(1), 
	@SUPPLIER_EMAIL      VARCHAR(60),
	@SUPPLIER_POSTALCODE CHAR(8),
    @SUPPLIER_RG         CHAR(20),    
    @SUPPLIER_BIRTHDATE  DATE        
) 

AS 

UPDATE SUPPLIER 
SET  
    SUPPLIER_CPF_CNPJ   = @SUPPLIER_CPF_CNPJ  ,
    SUPPLIER_NAME       = @SUPPLIER_NAME      ,
    SUPPLIER_TYPE       = @SUPPLIER_TYPE      ,
    SUPPLIER_EMAIL      = @SUPPLIER_EMAIL     ,
    SUPPLIER_POSTALCODE = @SUPPLIER_POSTALCODE,
    SUPPLIER_RG         = @SUPPLIER_RG        ,
    SUPPLIER_BIRTHDATE  = @SUPPLIER_BIRTHDATE     
WHERE  
    SUPPLIER_CPF_CNPJ = @SUPPLIER_CPF_CNPJ

GO 
SET QUOTED_IDENTIFIER OFF 
GO 
SET ANSI_NULLS ON 
GO 